### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Glatrix** [Glatrix/MonoPipeSharp#1]
- [x] Add Domain functionality
- [x] Add Class Functionality
- [x] Add Field Functionality
- [ ] Add Method Functionality
- [x] Give up on this project and come back a year later (maybe idk yet)
- [ ] Add Pipe Security? eg lock and unlock. (prob to support async)
- [ ] Add all pipe functions. 1-1 with CE
- [ ] Add null checks EVERYWHERE xD
- [ ] Come up with more checklist items than this.
